<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <PackageId>OptiStorage.Client</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" />
    <ProjectReference Include="..\OptiStorage.Contracts\OptiStorage.Contracts.csproj" />
  </ItemGroup>

</Project>
