<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OptiStorage.Contracts\OptiStorage.Contracts.csproj" />
    <ProjectReference Include="..\OptiStorage.Storage\OptiStorage.Storage.csproj" />
  </ItemGroup>

</Project>
